[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sll-core"
version = "2.0.2"
description = "Static Local Linearization for Differentiable Discrete Programming"
readme = "README.md"
authors = [
  { name = "jacksong", email = "15011462616@163.com" }
]
license = "MIT"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.8"
dependencies = [
  "torch >= 1.9.0"
]
keywords = ["differentiable", "discrete", "machine learning", "optimization"]

[project.urls]
"Homepage" = "https://github.com/jacksong-sourse/sll-core"
"Repository" = "https://github.com/jacksong-sourse/sll-core"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
